# Generated by Django 3.2 on 2021-06-03 23:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='userauth.user')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default.png', upload_to=profiles.models.user_profile_picture_path)),
            ],
            options={
                'ordering': ['user', 'created'],
            },
        ),
    ]
